anomaly_clean: false
batch_size: 8
conf_cache_level: 1
data_type: molecule
epochs: 200
freeze_layers:
- embed_tokens
- encoder
- classification_head
freeze_layers_reversed: true
kfold: 3
learning_rate: 0.0001
load_model_dir: /home/hank/code/unimol_tools/Result/ESP/fold_5/pretrain
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: mae
model_name: unimolv1
model_size: 84m
num_classes: 2
patience: 15
remove_hs: false
seed: 1
smi_strict: true
smiles_col: SMILES
split: random
split_group_col: scaffold
split_method: 3fold_random
split_seed: 1
target_col_prefix: TARGET
target_cols: TARGET_ESPmin,TARGET_ESPmax
target_normalize: auto
task: multilabel_regression
use_amp: true
use_cuda: true
use_ddp: false
use_gpu: all
warmup_ratio: 0.1
